# Generated by Django 4.0.2 on 2022-02-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentfile',
            old_name='product',
            new_name='item',
        ),
    ]
