# Generated by Django 4.0.2 on 2022-02-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_rename_product_contentfile_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentfile',
            name='customer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contentfile',
            name='item',
            field=models.CharField(default='', max_length=100),
        ),
    ]
