# Generated by Django 4.0.2 on 2022-02-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_clients_rename_client_clean_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clean_data',
            name='gems',
        ),
        migrations.AddField(
            model_name='clean_data',
            name='gems',
            field=models.CharField(default='', max_length=500),
        ),
    ]
