# Generated by Django 4.0.2 on 2022-02-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_remove_clean_data_gems_clean_data_gems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentfile',
            name='customer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contentfile',
            name='item',
            field=models.CharField(max_length=100),
        ),
    ]
