# Generated by Django 4.0.2 on 2022-02-18 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_alter_contentfile_customer_alter_contentfile_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentfile',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='deals.clients'),
        ),
        migrations.AlterField(
            model_name='contentfile',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gems', to='deals.gems'),
        ),
    ]
